name: Scala CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.11, adopt@1.8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Run tests
        run: sbt ++ fmtCheck test
